In [41]:
import yfinance as yf
import pandas as pd 
import numpy as np
#import statsmodels.api as sm
import matplotlib.pyplot as plt
pd.options.mode.chained_assignment = None  # default='warn'

df  = yf.download ('^BVSP', 
                   period = "1y",
                   interval = "1d")
                   #progress = False)

df = df[['Open','Adj Close']]
df['Dif %'] = ''

for i in range (1, len(df)):
    calc2 = df['Adj Close'][i] / df['Adj Close'][i-1] 
    calc = (calc2 *100) - 100
    df['Dif %'][i] = calc
    
#df.tail()

#REMOVER A ULTIMA LINHA
df.drop(index=df.index[-1],axis=0,inplace=True)
df = df.tail(10)

MediaFec = df['Adj Close'].mean()

print(MediaFec)
display(df)

[*********************100%***********************]  1 of 1 completed
111002.8

                Open  Adj Close     Dif %
Date
2022-08-26  113533.0   112299.0 -1.086037
2022-08-29  112296.0   112323.0  0.021372
2022-08-30  112323.0   110431.0 -1.684428
2022-08-31  110431.0   109523.0 -0.822233
2022-09-01  109524.0   110405.0   0.80531
2022-09-02  110409.0   110864.0  0.415742
2022-09-05  110868.0   112203.0  1.207786
2022-09-06  112203.0   109764.0 -2.173739
2022-09-08  109771.0   109916.0  0.138479
2022-09-09  109922.0   112300.0  2.168929