In [5]:
import yfinance as yf
import matplotlib.pyplot as plt
import pandas as pd
pd.options.mode.chained_assignment = None

ticker = input(f'Qual o ticker? ')
#ticker = 'asai3f'
dia = yf.Ticker(ticker+'.SA')
base = dia.history(period='1d', interval='5m')

# Criar coluna 'Dif' e efetuar a subtração
base['Dif'] = base['Close'] - base['Open']
# Criar coluna 'G/P' e efetuar calculo
base['G/P %'] = base['Dif'] / base['Open']
# Redefinir a tabela 'base' com as colunas desejadas
base = base[['Open','Close','Dif','G/P %','Volume']]
# Criar coluna 'Sinal' com o indicativo de C ou V
base['Sinal'] = ''
for i in range (1, len(base)):
    if base['Open'][i] < base['Close'][i]:
        base['Sinal'][i] = 'C'
    else:
        base['Sinal'][i] = 'V'
# Contar os 'V' e 'C' na tabela Sinal
cv = base['Sinal'].value_counts(dropna=False) 

# Transformar dados C ou V em lista
cv.to_list()
compra = cv[1]
venda = cv[0]
#print(f'Compra: {compra}')
#print(f'Venda: {venda}')

# Organizar por maiores ganhos
mediaGeral = base.sort_values(by=['G/P %'], ascending=False).head(50)
#medias

# Média dos ganhos
medias = mediaGeral[['G/P %']]
mediaGanho = float(medias.mean())
mediaGanho = round(mediaGanho,5)
print(mediaGanho)

venda = base[['Open','G/P %']]
venda[['Gatilho']] = base[['Open']] * mediaGanho + base[['Open']]
venda = round(venda,2)
#venda.tail(5)

dia = yf.Ticker('vale3.SA')
base = dia.history(period='1d', interval='5m')
#base.tail()

base = base[['Open','High','Low','Close']]
#candles = base.tail()

candles['h1'] = abs(candles['Close'] - candles['High'])*100
candles['h2'] = abs(candles['Open'] - candles['Close'])*100
candles['h3'] = abs(candles['Open'] - candles['Low'])*100
#candles

Qual o ticker? b3sa3f
Compra: 24
Venda: 45
0.00101

,Open,High,Low,Close,h1,h2,h3
Datetime,,,,,,,
2021-10-19 15:25:00-03:00,79.099998,79.129997,79.029999,79.089996,4.000092,1.000214,6.999969
2021-10-19 15:30:00-03:00,79.059998,79.160004,78.989998,79.070000,9.000397,1.000214,6.999969
2021-10-19 15:35:00-03:00,79.080002,79.080002,78.900002,78.959999,12.000275,12.000275,18.000031
2021-10-19 15:40:00-03:00,78.949997,79.029999,78.949997,78.989998,4.000092,4.000092,0.000000
2021-10-19 15:45:00-03:00,79.000000,79.000000,78.919998,78.980003,1.999664,1.999664,8.000183

In [27]:
#https://www.nelogica.com.br/conhecimento/artigos/indicadores-estudo/cinco-padroes-de-candlestick
#https://admiralmarkets.com/pt/educacao/aprender-trading/analise-forex/padroes-de-candlestick

candles['Sinal'] = ''

doji = (candles['h2'] < candles['h1']) & (candles['h2'] < candles['h3'])
martelo = ''
marteloInvertido = ''
estrelaC = ''
MarubozuAlta = ''
MarubozuBaixa = ''

for i in range(0,len(candles)):
    #if candles['h2'].iloc[i] < candles['h1'].iloc[i] and candles['h2'].iloc[i] < candles['h3'].iloc[i]:
    if (doji.iloc[i]) == True:
        candles['Sinal'].iloc[i] = 'Comprar'
    else:
        candles['Sinal'].iloc[i] = ''
candles

,Open,High,Low,Close,h1,h2,h3,Sinal
Datetime,,,,,,,,
2021-10-19 15:25:00-03:00,79.099998,79.129997,79.029999,79.089996,4.000092,1.000214,6.999969,Comprar
2021-10-19 15:30:00-03:00,79.059998,79.160004,78.989998,79.070000,9.000397,1.000214,6.999969,Comprar
2021-10-19 15:35:00-03:00,79.080002,79.080002,78.900002,78.959999,12.000275,12.000275,18.000031,
2021-10-19 15:40:00-03:00,78.949997,79.029999,78.949997,78.989998,4.000092,4.000092,0.000000,
2021-10-19 15:45:00-03:00,79.000000,79.000000,78.919998,78.980003,1.999664,1.999664,8.000183,